import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Download, RotateCcw, Leaf, AlertTriangle, Pill, FlaskConical, ShieldCheck, Sprout, Clock, ListChecks, Bug, ExternalLink } from 'lucide-react';
import { Reveal } from '@/components/ui/Reveal';
import CircularProgress from '@/components/ui/CircularProgress';
import { HealthBadge, Badge } from '@/components/ui/Badge';
import { useRouter } from '@/context/RouterContext';
import { useHistory } from '@/context/HistoryContext';
import { useToast } from '@/context/ToastContext';

function Section({ icon: Icon, title, children, color = 'brand' }) {
  const colors = {
    brand: 'bg-brand-100 text-brand-700 dark:bg-brand-950 dark:text-brand-300',
    earth: 'bg-earth-100 text-earth-700 dark:bg-earth-900/40 dark:text-earth-300',
    amber: 'bg-amber-100 text-amber-700 dark:bg-amber-950/60 dark:text-amber-300',
    red: 'bg-red-100 text-red-700 dark:bg-red-950/60 dark:text-red-300',
    blue: 'bg-blue-100 text-blue-700 dark:bg-blue-950/60 dark:text-blue-300',
  };
  return (
    <div className="card p-6">
      <div className="flex items-center gap-3">
        <span className={`flex h-10 w-10 items-center justify-center rounded-xl ${colors[color]}`}>
          <Icon size={20} />
        </span>
        <h3 className="font-display text-lg font-bold text-gray-900 dark:text-white">{title}</h3>
      </div>
      <div className="mt-4">{children}</div>
    </div>
  );
}

function BulletList({ items }) {
  return (
    <ul className="space-y-2.5">
      {items.map((item, i) => (
        <li key={i} className="flex items-start gap-2.5 text-sm text-gray-600 dark:text-gray-300">
          <span className="mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-brand-500" />
          {item}
        </li>
      ))}
    </ul>
  );
}

export default function ResultPage() {
  const { path, navigate } = useRouter();
  const { history } = useHistory();
  const toast = useToast();
  const [entry, setEntry] = useState(null);

  const queryId = useMemo(() => {
    const idx = path.indexOf('?');
    if (idx === -1) return null;
    const params = new URLSearchParams(path.slice(idx + 1));
    return params.get('id');
  }, [path]);

  useEffect(() => {
    if (queryId) {
      const found = history.find((h) => h.id === queryId);
      if (found) setEntry(found);
    }
  }, [queryId, history]);

  const handleDownload = () => {
    if (!entry) return;
    const lines = [
      'AI PLANT DISEASE DETECTION — REPORT',
      '=====================================',
      '',
      `Crop:           ${entry.crop}`,
      `Disease:        ${entry.diseaseName}`,
      `Status:         ${entry.isUncertain ? 'Uncertain' : entry.isHealthy ? 'Healthy' : 'Diseased'}`,
      `Confidence:     ${entry.confidence}%`,
      `Date:           ${new Date(entry.date).toLocaleString()}`,
      '',
      'DESCRIPTION',
      entry.description,
      '',
      'SYMPTOMS',
      ...entry.symptoms.map((s) => `- ${s}`),
      '',
      'CAUSES',
      ...entry.causes.map((s) => `- ${s}`),
      '',
      'RECOMMENDED MEDICINES',
      ...entry.medicines.map((s) => `- ${s}`),
      '',
      'ORGANIC TREATMENT',
      ...entry.organicTreatment.map((s) => `- ${s}`),
      '',
      'PREVENTION TIPS',
      ...entry.prevention.map((s) => `- ${s}`),
      '',
      'SUGGESTED FERTILIZER',
      entry.fertilizer,
      '',
      'EXPECTED RECOVERY TIME',
      entry.recoveryTime,
      '',
      'SOURCE',
      entry.source || 'Not provided',
      '',
      '-------------------------------------',
      'Generated by AI Plant Disease Detection System',
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `disease-report-${entry.diseaseId || 'result'}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Report downloaded.');
  };

  if (!entry) {
    return (
      <div className="flex min-h-[70vh] items-center justify-center px-4">
        <div className="text-center">
          <span className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-amber-100 text-amber-600 dark:bg-amber-950/60 dark:text-amber-400">
            <AlertTriangle size={30} />
          </span>
          <h1 className="mt-5 font-display text-2xl font-bold text-gray-900 dark:text-white">No result found</h1>
          <p className="mt-2 text-sm text-gray-500 dark:text-gray-400">
            We couldn't find a diagnosis for this link. Try analyzing a new image.
          </p>
          <button onClick={() => navigate('/detect')} className="btn-primary mt-6">
            <RotateCcw size={18} /> Go to Detection
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-gray-50 py-10 lg:py-14 dark:bg-gray-900/30">
      <div className="container-app">
        <Reveal>
          <button onClick={() => navigate('/detect')} className="btn-ghost mb-6 -ml-3">
            <ArrowLeft size={18} /> Back to Detection
          </button>
        </Reveal>

        <Reveal delay={80}>
          <div className="card overflow-hidden">
            <div className="grid gap-0 lg:grid-cols-2">
              <div className="relative bg-gray-100 dark:bg-gray-800">
                <img src={entry.image} alt={entry.diseaseName} className="h-72 w-full object-cover lg:h-full" />
                <div className="absolute inset-0 bg-gradient-to-t from-black/30 to-transparent" />
                <div className="absolute left-4 top-4">
                  {entry.isUncertain ? <Badge color="amber">Uncertain</Badge> : <HealthBadge isHealthy={entry.isHealthy} />}
                </div>
              </div>

              <div className="p-7 sm:p-9">
                <div className="flex flex-wrap items-center gap-2">
                  <Badge color="earth">{entry.crop}</Badge>
                  {entry.cropMismatch && entry.detectedCrop && (
                    <Badge color="amber">Image may be {entry.detectedCrop}</Badge>
                  )}
                </div>
                <h1 className="mt-4 font-display text-2xl font-extrabold text-gray-900 sm:text-3xl dark:text-white">
                  {entry.diseaseName}
                </h1>
                <p className="mt-3 text-sm leading-relaxed text-gray-600 dark:text-gray-400">
                  {entry.description}
                </p>

                <div className="mt-7 flex items-center gap-5">
                  <CircularProgress value={entry.confidence} size={130} label="Confidence" />
                  <div className="space-y-2">
                    <div className="flex items-center gap-2 text-sm">
                      <Leaf size={16} className="text-brand-500" />
                      <span className="text-gray-500 dark:text-gray-400">Status:</span>
                      <span className="font-semibold text-gray-900 dark:text-white">
                        {entry.isUncertain ? 'Uncertain' : entry.isHealthy ? 'Healthy' : 'Diseased'}
                      </span>
                    </div>
                    <div className="flex items-center gap-2 text-sm">
                      <Clock size={16} className="text-blue-500" />
                      <span className="text-gray-500 dark:text-gray-400">Analyzed:</span>
                      <span className="font-semibold text-gray-900 dark:text-white">
                        {new Date(entry.date).toLocaleDateString()}
                      </span>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </Reveal>

        <div className="mt-6 grid gap-5 lg:grid-cols-2">
          <Reveal delay={120}>
            <Section icon={ListChecks} title="Symptoms" color="amber">
              <BulletList items={entry.symptoms} />
            </Section>
          </Reveal>
          <Reveal delay={160}>
            <Section icon={Bug} title="Causes" color="red">
              <BulletList items={entry.causes} />
            </Section>
          </Reveal>
          <Reveal delay={200}>
            <Section icon={Pill} title="Recommended Medicines" color="earth">
              <BulletList items={entry.medicines} />
            </Section>
          </Reveal>
          {entry.organicTreatment?.length > 0 && (
            <Reveal delay={240}>
              <Section icon={FlaskConical} title="Organic Treatment" color="brand">
                <BulletList items={entry.organicTreatment} />
              </Section>
            </Reveal>
          )}
          <Reveal delay={280}>
            <Section icon={ShieldCheck} title="Prevention Tips" color="blue">
              <BulletList items={entry.prevention} />
            </Section>
          </Reveal>
          {(entry.fertilizer || entry.recoveryTime) && <div className="grid gap-5">
            <Reveal delay={320}>
              <Section icon={Sprout} title="Suggested Fertilizer" color="brand">
                <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-300">{entry.fertilizer}</p>
              </Section>
            </Reveal>
            <Reveal delay={360}>
              <Section icon={Clock} title="Expected Recovery Time" color="amber">
                <p className="text-sm leading-relaxed text-gray-600 dark:text-gray-300">{entry.recoveryTime}</p>
              </Section>
            </Reveal>
          </div>}
          {entry.source && (
            <Reveal delay={360}>
              <Section icon={ExternalLink} title="Information Source" color="blue">
                <p className="break-words text-sm leading-relaxed text-gray-600 dark:text-gray-300">{entry.source}</p>
              </Section>
            </Reveal>
          )}
        </div>

        <Reveal delay={120}>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row sm:justify-center">
            <button onClick={() => navigate('/detect')} className="btn-secondary">
              <RotateCcw size={18} /> Analyze Another Image
            </button>
            <button onClick={handleDownload} className="btn-primary">
              <Download size={18} /> Download PDF Report
            </button>
          </div>
        </Reveal>
      </div>
    </div>
  );
}
